set nowrap
set nu
set clipboard=unnamed
set nocompatible
set nobackup
set noswapfile
set history=1000
set sessionoptions+=globals
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set tabstop=4
set expandtab
set smarttab
set shiftwidth=4
set autoindent
set cindent
set si
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set mouse=a
set selection=exclusive
set selectmode=mouse,key

